### ISSUE TITLE
clarify why this is needed

### ISSUE THREAD

**Issue by 3052** [rkk3/ad-accelerator#1]
I do not get ads (for now). so can you clarify why this is needed? one of my lists hasnt even been updated in 12 days:

~~~
uBlock Origin: 1.53.0
Firefox: 101
listset (total-discarded, last-updated):
 default:
  user-filters: 29-0, never
  ublock-filters: 36499-76, 2d.4h.22m
  ublock-badware: 7526-10, 2d.4h.21m
  ublock-privacy: 662-0, 5d.14h.51m
  ublock-unbreak: 2197-0, 2d.4h.20m
  ublock-quick-fixes: 114-1, 9h.56m
  easylist: 75490-702, 11h.57m
  easyprivacy: 32876-724, 4d.14h.52m
  urlhaus-1: 10890-0, 22h.28m
  plowe-0: 3721-1, 12d.14h.56m
~~~

**Comment by ArjixWasTaken** [comment]
This is needed if you have disabled your adblocker for youtube.

**Comment by 3052** [comment]
> This is needed if you have disabled your adblocker for youtube.

why would anyone do that? you can enable the blocker and still use the site as expected, which was the point of my original comment

**Comment by rkk3** [comment]
The extension is a workaround for when traditional Adblocker's aren't allowed see https://github.com/rkk3/ad-accelerator#background. Youtube has been gradually rolling out their prohibition on Adblockers since this summer and isn't enforcing it consistently for everyone yet.

**Comment by 3052** [comment]
I have gotten those notifications on the YouTube site for a while, and updating the the blocker resolved the issue. it was a cat and mouse game for some weeks, but at least for now uBlock Origin seems to have "won". do you have evidence otherwise?
