### ISSUE TITLE
Channel 4 Player support also a code question

### ISSUE THREAD

**Issue by ciaranbrohan** [rkk3/ad-accelerator#12]
Hey I'm based in the uk, not sure if you use the channel 4 player/rte player, i've built a similar style of plugin as yours (using your code as inspiration) just like to poke around myself to understand the code.

I can do a pr to add support for both if you'd be interested, 

Secondly, I was wondering if there's a better way to handle this code: 

```       
const video = document.querySelector('video');
const adElement = document.querySelector('.video-ads.ytp-ad-module');
```

the check for the ad element and video seems doubled up? although there could be a good reason for it

**Comment by rkk3** [comment]
Sorry for the delay you're welcome to do a PR to support that site. 

There might be a better way of handling that, but at a high level we need the video element because thats what we manipulate & the ad element tells us if there are ads running.
