### ISSUE TITLE
removed extension but actual youtube content still fast-forwarding

### ISSUE THREAD

**Issue by dabido3** [rkk3/ad-accelerator#6]
i removed the extension because it started to fast-forward the actual youtube content as well as the ads...but even with the extension removed, it's *still* fast forwarding the content... not sure how to revert things to normal now

**Comment by rkk3** [comment]
Sorry to hear that. Have you tried closing chrome after removing it and seeing if the issue still persists?

**Comment by jovanzers** [comment]
> yep; quit browser and re-opened and it's still happening. quite hilarious for a few minutes, but I would like to be able to watch YouTube again.. hah

How about in incognito mode?

**Comment by rkk3** [comment]
Have you tried clearing your cookies & cache?

**Comment by dabido3** [comment]
ah silly me.. cookies/cache cleared and it's back to normal. thanks

**Comment by rkk3** [comment]
No problem, glad its resolved & I'm sorry that happened for you.  I haven't gotten any other reports of it speeding up Youtube content and unfortunately don't know how to reproduce the issue.
