### ISSUE TITLE
you are not wrong

### ISSUE THREAD

**Issue by MM502** [rkk3/ad-accelerator#7]
"Perhaps I'm wrong to feel they violated the spirit in which I shared the project".

No, you are not wrong. I hope that other person with the Discord server has not ruined your enthusiasm to release future projects open source.

I do not even use Chrome but saw this story with your GitHub post mentioned. Greedy people with no shame who present the work of others as theirs have always existed. You are an asset to the community - they are not.

**Comment by rkk3** [comment]
I really appreciate the support. Thanks for reading the post. It has been an incredibly odd week
