### ISSUE TITLE
After accelerating an ad, while the Youtube player is in a PiP mode, it forgets to unmute. (Opera GX)

### ISSUE THREAD

**Issue by dadanda** [rkk3/ad-accelerator#9]
As the title says, when I watch in PiP, an ad plays and accelerates, it forgets to unmute.
I am using OperaGX and another extension (YouTube Enhancer) that adds PiP functionality to YouTube.
When I do, it forgets to unmute the player when an ad plays out.
I don't know how to show it because the ad plays out very quickly and there are no console logs that I think I can show.

My workaround for this is a userscript that has a function of muting and skipping ads to cover for the unmuting.

**Comment by rkk3** [comment]
Hi thanks for letting us know!

To clarify the issue, this is not in Youtube's multiplayer mode but in a Pip mode that is created by another extension? 

Does the speed remain 16x after the add finishes? I'm surprised only the muting would persist and not the playbackspeed as well. If it is only the mute, would having something like a configuration panel where you can turn off the muting on YouTube be an acceptable solution for you?
